
const products = [
  {
    id: 1,
    name: "iPhone 13 mini 128GB, Pink (Unlocked)",
    price: 599.0,
    originalPrice: 699.0,
    rating: 4.5,
    reviews: 128,
    image: `${img1}`,
    freeShipping: true,
    description:
      "A15 Bionic chip for lightning-fast performance. Advanced dual-camera system for incredible photos in any light. Cinematic mode adds shallow depth of field and shifts focus automatically.",
  },
  {
    id: 7,
    name: "iPhone 13 mini 128GB, Pink (Unlocked)",
    price: 599.0,
    originalPrice: 699.0,
    rating: 4.5,
    reviews: 128,
    image: `${img1}`,
    freeShipping: true,
    description:
      "A15 Bionic chip for lightning-fast performance. Advanced dual-camera system for incredible photos in any light. Cinematic mode adds shallow depth of field and shifts focus automatically.",
  },
  {
    id: 2,
    name: "Samsung Galaxy X6 5G",
    price: 899.0,
    originalPrice: 1199.0,
    rating: 4.3,
    reviews: 256,
    image: `${img2}`,
    freeShipping: true,
    description:
      "Pro-grade Camera with 108MP resolution. 8K Video recording capability. S Pen compatibility. Dynamic AMOLED 2X display with 120Hz refresh rate.",
  },
  {
    id: 3,
    name: "iPad Pro 11-inch (3rd generation)",
    price: 799.0,
    originalPrice: 899.0,
    rating: 4.7,
    reviews: 89,
    image: `${img3}`,
    freeShipping: true,
    description:
      "M1 chip delivers next-level performance. Stunning 11-inch Liquid Retina display with ProMotion, True Tone, and P3 wide color. Ultra Wide front camera with Center Stage.",
  },
  {
    id: 4,
    name: "MacBook Air 13-inch M2 Chip",
    price: 1199.0,
    originalPrice: 1299.0,
    rating: 4.8,
    reviews: 342,
    image: `${img4}`,
    freeShipping: true,
    description:
      "Supercharged by M2 chip. Up to 18 hours of battery life. Fanless design for silent operation. 13.6-inch Liquid Retina display with 500 nits of brightness.",
  },
  {
    id: 5,
    name: "Apple Watch Series 8 GPS 45mm",
    price: 399.0,
    originalPrice: 429.0,
    rating: 4.6,
    reviews: 167,
    image: `${img5}`,
    freeShipping: true,
    description:
      "Advanced health sensors including temperature sensing. Crash Detection. Water resistant to 50 meters. All-day battery life up to 18 hours.",
  },
  {
    id: 6,
    name: "Sony WH-1000XM4 Wireless Headphones",
    price: 279.0,
    originalPrice: 349.0,
    rating: 4.4,
    reviews: 523,
    image: `${img6}`,
    freeShipping: true,
    description:
      "Industry-leading noise canceling with Dual Noise Sensor technology. 30-hour battery life with quick charge. Touch sensor controls for pause, play, skip tracks.",
  },
  {
    id: 6,
    name: "Sony WH-1000XM4 Wireless Headphones",
    price: 279.0,
    originalPrice: 349.0,
    rating: 4.4,
    reviews: 523,
    image: `${img6}`,
    freeShipping: true,
    description:
      "Industry-leading noise canceling with Dual Noise Sensor technology. 30-hour battery life with quick charge. Touch sensor controls for pause, play, skip tracks.",
  },
  {
    id: 7,
    name: "Sony WH-1000XM4 Wireless Headphones",
    price: 279.0,
    originalPrice: 349.0,
    rating: 4.4,
    reviews: 523,
    image: `${img6}`,
    freeShipping: true,
    description:
      "Industry-leading noise canceling with Dual Noise Sensor technology. 30-hour battery life with quick charge. Touch sensor controls for pause, play, skip tracks.",
  },
  {
    id: 8,
    name: "Sony WH-1000XM4 Wireless Headphones",
    price: 279.0,
    originalPrice: 349.0,
    rating: 4.4,
    reviews: 523,
    image: `${img6}`,
    freeShipping: true,
    description:
      "Industry-leading noise canceling with Dual Noise Sensor technology. 30-hour battery life with quick charge. Touch sensor controls for pause, play, skip tracks.",
  },
  {
    id: 9,
    name: "Sony WH-1000XM4 Wireless Headphones",
    price: 279.0,
    originalPrice: 349.0,
    rating: 4.4,
    reviews: 523,
    image: `${img6}`,
    freeShipping: true,
    description:
      "Industry-leading noise canceling with Dual Noise Sensor technology. 30-hour battery life with quick charge. Touch sensor controls for pause, play, skip tracks.",
  },
]